# Generated by Django 4.0.3 on 2022-10-29 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_alter_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='from_user',
            field=models.ForeignKey(blank=True, db_column='from_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_sends', to=settings.AUTH_USER_MODEL, verbose_name='From User'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='to_user',
            field=models.ForeignKey(blank=True, db_column='to_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_receives', to=settings.AUTH_USER_MODEL, verbose_name='To User'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_type',
            field=models.CharField(choices=[('Debit', 'debit'), ('Credit', 'credit'), ('Default_amount', 'default_amount')], db_column='transaction_type', max_length=25, verbose_name='Transaction Type'),
        ),
    ]
