# Generated by Django 4.0.3 on 2022-10-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transactionhistory_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency_type',
            field=models.CharField(db_column='currency_type', default='BDT', max_length=125, verbose_name='Currency Type'),
        ),
    ]
